// generated by tools/m68k_timing/gen_cycle_rom.py --misc, do not edit
// 4E70-4E77: opcode[2:0] selects the instruction, not a register
always @* case(opc_l[2:0])
	3'd0: misc_e = 20'h801FE;   // RESET Instruction  cc 518 head 0 tail 0
	3'd1: misc_e = 20'h80004;   // NOP  cc 2 head 0 tail 0
	3'd2: misc_e = 20'h80010;   // STOP  cc 8 head 0 tail 0
	3'd3: misc_e = 20'h80224;   // RTE (Normal Four Word)  cc 18 head 1 tail 0
	3'd4: misc_e = 20'h80414;   // RTD  cc 10 head 2 tail 0
	3'd5: misc_e = 20'h80212;   // RTS  cc 9 head 1 tail 0
	3'd6: misc_e = 20'h80808;   // TRAPV (No Trap)  cc 4 head 4 tail 0
	3'd7: misc_e = 20'h80218;   // RTR  cc 12 head 1 tail 0
endcase
